### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by Neus252** [3akep/MM5451SEG#1]
there is  a typo in mm5451seg.cpp line 57 
ase 5: case '5': case 'S': case 's': myBit = 0b10110111; break;

should be 
case 5: case '5': case 'S': case 's': myBit = 0b10110111; break;

just so you know it aint compile in the current state :) thx for the code it works great !

**Comment by 3akep** [comment]
Thanks, fixed! Strange typo, How I test it?! =)
